[google_service_account]
type = "service_account"
project_id = "btc-ai-model-storage"
private_key_id = "129a2d0ff9b5af3ecad4eb42f465947ce76b9759"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDq5SLHF4cEkX73
7PTCQclmF53HI6BpVDnFp5i949c0t7vY1BQRglC3+WbJEEx/W2FgKO1I088wO4oO
8DUU/3Ml1miD/hpziQqDR2gCv62UoH8AylkmeZsmOZrA66fyVjm4b8pthU5D4w4w
hxjcHeVzfZ1H3C853u+KPf6VBTCeE5rFpY1XcnXLawCS+YFRuSqYQtyTEZgOPTjs
oLU5Wr/qXW5gKb7bEnWYsABCLvEnIkAwFqLQS+wx4qqTEAHzFFtm0IsbJhvY5ABm
54KdTScMlR4P8oubhs3NCrhmgWjj8G+AB2Qtja5urPk5Wb8EnfnfD6SqBmMLxh+M
i3yFuqT5AgMBAAECggEAElg5Tlery4NKaXXnypkFL9Q11gTWBQvXJDTZ1LCr0Lnt
sXokpBZrk+amLJs5gjPCh9ZCa87g7jkkJ9UCLETj+wdC69YHPlEsUULdIGPUXFhp
esgSzNKv930FtT3iRKaPxPP0GPgRe/NKWydd3Wj3T7z2cNOFG62pwv/i90Prv1iN
zXU55jr2I3L1z6iyyBzEcLNjnjxRnd3qD9KrNskHVhl1ytSMhYVyzLAKQPmuVDIH
aVmqLDvnZVJX9iM/+ZnRezAlXILfxD46qmlKqdqrs2PAOmGv2P19fC7ggA0WGPlM
DjHtrDsTxKoxyNNCXJo447XmR8c8ezC0nJmuhu3uAQKBgQD5wub6gOLzvwx45Ns8
h1ntpeo1aH5buoZvyXGjIwLwaqk9K9F1gVnhjWODZuR/BWOiiDhi5yQ9DJfPsXa8
VoTABnDAXxDaC79RyaOKx9VGr/kQZYxw1s+8toEl9E8hnKeFJD9+RehXs9Ert4o6
kNkB4Yo4pIlF33kN0kFXnbab+QKBgQDwwyvX043TlKX9zVQT27aHHHG4en48YVeU
65QNporsA8JaOp4RWlKdamB1wN9eeAGVWK/x9tSzBfHZEa35Li7+rC5lx6NBEfrC
g5vekWQKuSTE6/AgtisR9GUmg0XdfUIvy46vZAnSvDX/pfIer9XzLfX1/BWtmeER
NlRw+gyRAQKBgQCaKpEyjT4JoKLNOM6O1SlQRLqFzwM4EbGL7Pck8KaOyfe/F34K
Hxbg38pOQMPIGAaBO746Zlx7BnvqqqsU4/67HP6Z79RSEzA8Bs/ZCTJ/mH2Pfm8q
85106d5cFCqIH89ToqVCh1o8UHVLm9ZKAkDBJXuRLRbCt4dcXa0RrPsb2QKBgA9z
lya8zwdbLOQC/3hey3IUY0ABrIRXgvVtwQy3OYc4HosH5AkdENxFbXdhL3Syovdg
v7n5q2Dp6sGRnua1DhMOHdQuYc3VR5CgPaqlDhSaGUACHGEdD9qRIsS7/Ang9hR3
LesXsoGxzo1fqxBJHKQEuRpWWVXQ4F7oa7bsdU4BAoGBAJAeXUeeYWFZGGP52Xji
KHyO06EBI2L+6ntGXDuHPekXKhMG11ijOZVyR3pmjs7RnfPka9QULyyRztH94Osm
r7QCvDNZ4Nm8H4xUR5g9kBDPxYeIgGyCC1SyH/WOK0nVweU6mC28sek17q7KKur6
F6kfdahjttZHjiEcy7A4YEnj
-----END PRIVATE KEY-----"""
client_email = "streamlit-ai-bot@btc-ai-model-storage.iam.gserviceaccount.com"
client_id = "107302488333262807279"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-ai-bot%40btc-ai-model-storage.iam.gserviceaccount.com"

[pushover]
user = "u4bs3eqg8gqsv8npdxrcqp8iezf4ad"
token = "asz6u3njxpr3ys94ea4uq3deed4u1z"
