[google_service_account]
[google_service_account]
type = "service_account"
project_id = "btc-ai-model-storage"
private_key_id = "129a2d0ff9b5af3ecad4eb42f465947ce76b9759"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDq5SLHF4cEkX73
7PTCQclmF53HI6BpVDnFp5i949c0t7vY1BQRglC3+WbJEEx/W2FgKO1I088wO4oO
8DUU/3Ml1miD/hpziQqDR2gCv62UoH8AylkmeZsmOZrA66fyVjm4b8pthU5D4w4w
hxjcHeVzfZ1H3C853u+KPf6VBTCeE5rFpY1XcnXLawCS+YFRuSqYQtyTEZgOPTjs
oLU5Wr/qXW5gKb7bEnWYsABCLvEnIkAwFqLQS+wx4qqTEAHzFFtm0IsbJhvY5ABm
54KdTScMlR4P8oubhs3NCrhmgWjj8G+AB2Qtja5urPk5Wb8EnfnfD6SqBmMLxh+M
i3yFuqT5AgMBAAECggEAElg5Tlery4NKaXXnypkFL9Q11gTWBQvXJDTZ1LCr0Lnt
...
F6kfdahjttZHjiEcy7A4YEnj
-----END PRIVATE KEY-----"""
client_email = "streamlit-ai-bot@btc-ai-model-storage.iam.gserviceaccount.com"
client_id = "107302488333262807279"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-ai-bot%40btc-ai-model-storage.iam.gserviceaccount.com"

[pushover]
user = "u4bs3eqg8gqsv8npdxrcqp8iezf4ad"
token = "apccb8tmg8j9pupcirg1acfkg3pzaj"
